"use client";

import Head from "next/head";
import NavicationHome from "@/app/components/NavicationHome";
import Footer from "@/app/components/Footer";
import { useEffect, useState } from "react";
import SidebarFilter from "@/app/components/SidebarFilter";
import Link from "next/link";
import Image from "next/image";
import { useParams } from "next/navigation";
import NavicationHomeSubpage from "@/app/components/NavicationHomeSubpage";
import FooterSubpage from "@/app/components/FooterSubpage";
import ModalDeatils from "@/app/components/ModalDeatils";

export default function CategorySearchPage() {
  const [isToggled, setIsToggled] = useState(false);
  const [selectedIconId, setSelectedIconId] = useState(null);
  const [icons, setIcons] = useState([]);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [isLoading, setIsLoading] = useState(false);
  const [totalIcons, setTotalIcons] = useState(0);

  const params = useParams();
  const category = params.category;

  const [filters, setFilters] = useState({
    categories: [category],
    colors: [],
    types: [],
  });

  const handleToggle = () => setIsToggled((prev) => !prev);

  const mianmenu = [
    { id: 1, title: "Icons", link: "/icons" },
    { id: 2, title: "Interface Icons", link: "/interface" },
    { id: 3, title: "Stickers", link: "/interface" },
    { id: 5, title: "Animated icons", link: "/interface" },
  ];

  useEffect(() => {
    const fetchIcons = async () => {
      setIsLoading(true);
      try {
        const query = new URLSearchParams();
        query.append("page", page);
        query.append("limit", 20);

        if (filters.categories.length)
          filters.categories.forEach(c => query.append("categories[]", c));
        if (filters.colors.length)
          filters.colors.forEach(c => query.append("colors[]", c));
        if (filters.types.length)
          filters.types.forEach(t => query.append("types[]", t));
        if (filters.tag)
          query.append("tag", filters.tag);

        const finalURL = `https://iconsguru.ascinatetech.com/api/icons?${query.toString()}`;

        const response = await fetch(finalURL);
        const data = await response.json();

        if (data?.icons?.data && Array.isArray(data.icons.data)) {
          setIcons(data.icons.data);
          setTotalPages(data.icons.last_page || 1);
          setTotalIcons(data.icons.total || 0);
        } else {
          console.error("❌ Unexpected data.icons format:", data);
          setIcons([]);
        }
      } catch (error) {
        console.error("🚨 Error fetching icons:", error);
        setIcons([]);
      } finally {
        setIsLoading(false);
      }
    };

    fetchIcons();
  }, [page, filters]);




  return (
    <>
      <Head>
        <title>Listing page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body className="lesting-searchings">
        <div
          className={`totals-sections-mains01 ${isToggled ? "swowpactive" : ""}`}
        >
          <aside className="sidebars-subpages  pt-3">
            <Link
              href="/"
              className="looso-shape pe-4 ps-3 d-flex align-items-center"
            >
              <div className="isons">
                <Image
                  loading="lazy"
                  src="/shape-icons015.svg"
                  alt="iconsguru"
                  width={33}
                  height={34}
                />
              </div>
              <div className="text-loghos">
                <Image
                  loading="lazy"
                  src="/full-text015.svg"
                  alt="iconsguru"
                  width={170}
                  height={25}
                />
              </div>
            </Link>
            <div className="slider-filtersr-div">
              <button
                onClick={handleToggle}
                className="btn pe-4 ps-3 w-100 comon_heading01 d-flex align-items-center filters-btn"
              >
                <span className="icpn-svg">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="25"
                    height="25"
                    fill="currentColor"
                    className="bi bi-filter"
                    viewBox="0 0 16 16"
                  >
                    <path d="M6 10.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5m-2-3a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m-2-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5" />
                  </svg>
                </span>
                <h4 className="ms-2">
                  Filter
                  <span className="arose">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      className="bi bi-arrow-left"
                      viewBox="0 0 16 16"
                    >
                      <path
                        fillRule="evenodd"
                        d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"
                      />
                    </svg>
                  </span>
                </h4>
              </button>
              <SidebarFilter
                onFilterChange={setFilters}
                showCategoryFilter={false}
              />
            </div>
            <SidebarFilter
              onFilterChange={(newFilters) => {
                setFilters((prev) => ({
                  ...prev,
                  ...newFilters,
                  categories:
                    newFilters.categories.length > 0
                      ? newFilters.categories
                      : [category],
                }));
              }}
              showCategoryFilter={true}
            />
          </aside>

          <div className="rights-sections-sub">
            <main className="listing-pages no-border floate-start w-100 mb-5 mt-0 pt-0">
              <NavicationHomeSubpage />
              <div className="main-divs g-col-6">
                <div className="serchings-div-filets01">
                  <ul className="d-flex align-items-center menus-list01">
                    {mianmenu.map((page) => (
                      <li className="nav-item" key={page.id}>
                        <Link href={page.link} className="nav-link">
                          {page.title}
                        </Link>
                      </li>
                    ))}
                  </ul>
                </div>

                <p className="spaceing-lefts">
                  Showing{" "}
                  <strong className="serch-data">
                    {totalIcons} {category}
                  </strong>
                </p>

                <div className="related-iconstext">
                  <div className="d-flex align-items-center">
                    <p className="m-0"> Related: </p>
                    <ul className="d-flex ms-2 align-items-center flex-wrap mb-0 p-0">
                      <li>
                        <Link href="/" className="btn-mores-tex">
                          {" "}
                          Design{" "}
                        </Link>
                      </li>
                      <li>
                        <Link href="/" className="btn-mores-tex">
                          {" "}
                          Building{" "}
                        </Link>
                      </li>
                      <li>
                        <Link href="/" className="btn-mores-tex">
                          {" "}
                          Architecture{" "}
                        </Link>
                      </li>
                      <li>
                        <Link href="/" className="btn-mores-tex">
                          {" "}
                          Furniture{" "}
                        </Link>
                      </li>
                      <li>
                        <Link href="/" className="btn-mores-tex">
                          {" "}
                          Construction{" "}
                        </Link>
                      </li>
                      <li>
                        <Link href="/" className="btn-mores-tex">
                          {" "}
                          Construction{" "}
                        </Link>
                      </li>
                      <li>
                        <Link href="/" className="btn-mores-tex">
                          {" "}
                          Property{" "}
                        </Link>
                      </li>
                      <li>
                        <Link href="/" className="btn-mores-tex">
                          {" "}
                          Estate{" "}
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>

                <div className="tabsd_divs d-inline-block w-100 mt-4">
                  <div className="new-icons-bm news-colors-div row gy-2 g-lg-2 mt-0">
                    {isLoading ? (
                      <div className="loading-animations row w-100 show-grids">
                        {[...Array(18)].map((_, i) => (
                          <div className="loading-animations row w-100 show-grids" key={i}>
                               <div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div>
                               <div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div>
                               <div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div>
                          </div>
                        ))}
                      </div>
                    ) : Array.isArray(icons) && icons.length > 0 ? (
                      icons.map((icon) => {
                        return (
                          <button
                            key={icon.Id}
                             data-bs-toggle="modal"
                             data-bs-target="#exampleModal"
                            className="col-lg-2 svg-item position-relative"
                            onClick={() => setSelectedIconId(icon.Id)}
                          >
                            <span className="tags-frees">Free</span>
                            <span className="btn icons-list p-0">
                              {icon.type === "Animated" ? (
                                <img
                                  src={`https://iconsguru.ascinatetech.com/public/uploads/animated/${encodeURIComponent(
                                    icon.icon_svg
                                  )}`}
                                  alt={icon.icon_name}
                                  style={{ width: "100%", height: "100%" }}
                                />
                              ) : (
                                <span
                                  dangerouslySetInnerHTML={{
                                    __html: icon.icon_svg,
                                  }}
                                ></span>
                              )}
                            </span>
                          </button>
                        );
                      })
                    ) : (
                      <div className="col no-found-div w-100">
                        <div className="not-imgs text-center">
                          <figure className="m-0">
                            <Image
                              loading="lazy"
                              src="/nofound.png"
                              alt="iconsguru"
                              width={249}
                              height={219}
                            />
                          </figure>
                          <h2>No results found</h2>
                          <p>Try updating your search terms or filters</p>
                        </div>
                      </div>
                    )}
                  </div>

                  

                   {/* Pagination */}
                              {totalPages > 1 && (
                              <div className="d-flex align-items-center justify-content-center my-5 gap-2 flex-wrap">
                                <button
                                  className="btn btn-pre"
                                  onClick={() => setPage((prev) => Math.max(prev - 1, 1))}
                                  disabled={page === 1}
                                >
                                  ← Previous
                                </button>

                                {[...Array(totalPages)].map((_, index) => {
                                  const pageNum = index + 1;
                                  return (
                                    <button
                                      key={pageNum}
                                      onClick={() => setPage(pageNum)}
                                      className={`btn btn-sm ${page === pageNum ? "btn-primary" : "btn-outline-secondary"}`}
                                    >
                                      {pageNum}
                                    </button>
                                  );
                                })}

                                <button
                                  className="btn btn-next"
                                  onClick={() => setPage((prev) => Math.min(prev + 1, totalPages))}
                                  disabled={page === totalPages}
                                >
                                  Next →
                                </button>
                              </div>
                              )}

                </div>
              </div>
            </main>
          </div>
        </div>

        {/* Modal */}
        <ModalDeatils id={selectedIconId ?? null} />
      </body>
    </>
  );
}
