"use client";
import Head from "next/head";
import { useEffect, useState } from "react";
import SidebarFilter from "@/app/components/SidebarFilter";
import Link from "next/link";
import Image from "next/image";
import { useParams } from "next/navigation";
import NavicationHomeDetails from "@/app/components/NavicationHomeDetails";
import ModalDeatils from "@/app/components/ModalDeatils";

export default function CategorySearchPage() {
  const [isToggled, setIsToggled] = useState(false);
  const [selectedIconId, setSelectedIconId] = useState(null);
  const [icons, setIcons] = useState([]);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [isLoading, setIsLoading] = useState(false);
  const [totalIcons, setTotalIcons] = useState(0);

  const params = useParams();
  const category = params.category;

  const [filters, setFilters] = useState({
    categories: [category],
    colors: [],
    types: [],
  });

  const handleToggle = () => setIsToggled((prev) => !prev);

  const handleFilterChange = (newFilters) => {
    setPage(1);
    setFilters((prev) => ({
      ...prev,
      ...newFilters,
      categories: [category], // 🔐 force category
    }));
  };

  useEffect(() => {
    const fetchIcons = async () => {
      setIsLoading(true);
      try {
        const query = new URLSearchParams();
        query.append("page", page);
        query.append("limit", 20);

        if (filters.categories.length)
          filters.categories.forEach(c => query.append("categories[]", c));
        if (filters.colors.length)
          filters.colors.forEach(c => query.append("colors[]", c));
        if (filters.types.length)
          filters.types.forEach(t => query.append("types[]", t));
        if (filters.tag)
          query.append("tag", filters.tag);

        const finalURL = `https://iconsguru.ascinatetech.com/api/icons?${query.toString()}`;

        const response = await fetch(finalURL);
        const data = await response.json();

        if (data?.icons?.data && Array.isArray(data.icons.data)) {
          setIcons(data.icons.data);
          setTotalPages(data.icons.last_page || 1);
          setTotalIcons(data.icons.total || 0);
        } else {
          console.error("❌ Unexpected data.icons format:", data);
          setIcons([]);
        }
      } catch (error) {
        console.error("🚨 Error fetching icons:", error);
        setIcons([]);
      } finally {
        setIsLoading(false);
      }
    };

    fetchIcons();
  }, [page, filters]);




  return (
    <>
      <Head>
        <title>Listing page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className={`totals-sections-mains01 new-lisiting ${isToggled ? "swowpactive" : ""}`}>
        <NavicationHomeDetails />
        <div className="main-listings01 float-start w-100 only-listings01">
          <div className="container">
            <div className="row align-items-start">
              <div className="col-lg-3 slil">
                <aside className="sidebars-subpages pt-2 p-4 d-inline-block w-100">
                  <div className="slider-filtersr-div">


                    <h4 className="ms-0 filters-text w-100">
                      Filter
                      <span className='arose'>  <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-filter" viewBox="0 0 16 16">
                        <path d="M6 10.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5m-2-3a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m-2-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5" />
                      </svg>  </span>
                    </h4>
                    <SidebarFilter
                      onFilterChange={handleFilterChange}
                      showCategoryFilter={false}
                    />
                  </div>
                </aside>
                <aside className="sidebars-subpages cmb-borad01 p-4 d-none d-inline-lg-block w-100 bd-md015 pt-2 mt-5">
                  <Link href="/" >
                    <div className="sm-logs mt-3 text-center">
                      <Image loading="lazy" src="/icon-logos.jpg"
                        alt="iconsguru"
                        width={223}
                        height={53} />
                    </div>

                    <p className="text-center mb-0 mt-0"> Free accessories that allow you to organize, create and save time on your designs! </p>
                    <div className="text-center">
                      <Image loading="lazy" src="/undraw_learning-to-sketch_uaxi.svg"
                        alt="iconsguru"
                        width={223}
                        height={223} />
                    </div>
                  </Link>
                  <Link href="/icon" className="btn d-table mx-auto gts-strts-no">
                    Get Started now
                  </Link>
                </aside>
              </div>
              <div className="col-lg-9">
                <div className="rights-sections-sub no-border">
                  <main className="listing-pages floate-start w-100 mb-5">
                    <div className="main-divs g-col-6 pt-0">
                      <p className="spaceing-lefts">
                        <button onClick={handleToggle} className="btn px-0 me-3">

                          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="rgba(0,0,0,1)"><path d="M22.0003 13.0001L22.0004 11.0002L5.82845 11.0002L9.77817 7.05044L8.36396 5.63623L2 12.0002L8.36396 18.3642L9.77817 16.9499L5.8284 13.0002L22.0003 13.0001Z"></path></svg>

                        </button>
                        Showing{" "}
                        <strong className="serch-data">
                          {totalIcons} {category}
                        </strong>
                      </p>

                      <div className="related-iconstext">
                        <div className="d-flex align-items-center">
                          <p className="m-0"> Related: </p>
                          <ul className="d-flex ms-2 align-items-center flex-wrap mb-0 p-0">
                            <li>
                              <Link href="/" className="btn-mores-tex">
                                {" "}
                                Design{" "}
                              </Link>
                            </li>
                            <li>
                              <Link href="/" className="btn-mores-tex">
                                {" "}
                                Building{" "}
                              </Link>
                            </li>
                            <li>
                              <Link href="/" className="btn-mores-tex">
                                {" "}
                                Architecture{" "}
                              </Link>
                            </li>
                            <li>
                              <Link href="/" className="btn-mores-tex">
                                {" "}
                                Furniture{" "}
                              </Link>
                            </li>
                            <li>
                              <Link href="/" className="btn-mores-tex">
                                {" "}
                                Construction{" "}
                              </Link>
                            </li>
                            <li>
                              <Link href="/" className="btn-mores-tex">
                                {" "}
                                Construction{" "}
                              </Link>
                            </li>
                            <li>
                              <Link href="/" className="btn-mores-tex">
                                {" "}
                                Property{" "}
                              </Link>
                            </li>
                            <li>
                              <Link href="/" className="btn-mores-tex">
                                {" "}
                                Estate{" "}
                              </Link>
                            </li>
                          </ul>
                        </div>
                      </div>
                      <div className="tabsd_divs d-inline-block w-100 mt-4">
                        <div className="new-icons-bm news-colors-div mt-0">
                          {isLoading ? (
                            <div className="loading-animations row w-100 show-grids">
                              {[...Array(18)].map((_, i) => (
                                <div className="loading-animations row w-100 show-grids" key={i}>
                                  <div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div>
                                  <div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div>
                                  <div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div><div className="df01 col-lg-2"></div>
                                </div>
                              ))}
                            </div>
                          ) : Array.isArray(icons) && icons.length > 0 ? (
                            icons.map((icon) => {
                              return (
                                <div
                                  key={icon.Id}

                                  className="svg-item position-relative"
                                  onClick={() => setSelectedIconId(icon.Id)}
                                >
                                  <button className="tags-frees" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal"> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="currentColor"><path d="M6.41421 15.89L16.5563 5.74785L15.1421 4.33363L5 14.4758V15.89H6.41421ZM7.24264 17.89H3V13.6473L14.435 2.21231C14.8256 1.82179 15.4587 1.82179 15.8492 2.21231L18.6777 5.04074C19.0682 5.43126 19.0682 6.06443 18.6777 6.45495L7.24264 17.89ZM3 19.89H21V21.89H3V19.89Z"></path></svg></button>
                                  <span className="btn icons-list sm-icons015 p-0">
                                    {icon.type === "Animated" ? (
                                      <img
                                        src={`https://iconsguru.ascinatetech.com/public/uploads/animated/${encodeURIComponent(
                                          icon.icon_svg
                                        )}`}
                                        alt={icon.icon_name}
                                        style={{ width: "100%", height: "100%" }}
                                      />
                                    ) : (
                                      <span
                                        dangerouslySetInnerHTML={{
                                          __html: icon.icon_svg,
                                        }}
                                      ></span>
                                    )}
                                  </span>
                                </div>
                              );
                            })
                          ) : (
                            <div className="col no-found-div w-100">
                              <div className="not-imgs text-center">
                                <figure className="m-0">
                                  <Image
                                    loading="lazy"
                                    src="/nofound.png"
                                    alt="iconsguru"
                                    width={249}
                                    height={219}
                                  />
                                </figure>
                                <h2>No results found</h2>
                                <p>Try updating your search terms or filters</p>
                              </div>
                            </div>
                          )}
                        </div>
                        {/* Pagination */}
                        {totalPages > 1 && (
                          <div className="d-flex align-items-center paginnations justify-content-center justify-content-lg-end my-5 gap-2 flex-wrap">
                            <div className="text-muted text-shows">
                              Page <strong>{page}</strong> of <strong>{totalPages}</strong>
                            </div>

                            {[...Array(totalPages)].map((_, index) => {
                              const pageNum = index + 1;
                              return (
                                <button
                                  key={pageNum}
                                  onClick={() => setPage(pageNum)}
                                  className={`btn btn-sm ${page === pageNum ? "btn-actives" : "btn-outline-secondary"}`}
                                >
                                  {pageNum}
                                </button>
                              );
                            })}

                          </div>
                        )}

                      </div>
                    </div>
                  </main>
                </div>
              </div>
            </div>
          </div>
        </div>



      </div>

      {/* Modal */}
      <ModalDeatils id={selectedIconId ?? null} />

    </>
  );
}
